# Generated by Django 4.1 on 2022-09-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gardnerdenverlog',
            options={'verbose_name': 'Gardner Denver Log', 'verbose_name_plural': 'Gardner Denver Logs'},
        ),
        migrations.AlterModelOptions(
            name='maintenancelog',
            options={'verbose_name': 'Maintenance Log', 'verbose_name_plural': 'Maintenance Logs'},
        ),
    ]
