from typing import Dict

alarm_descriptions: Dict[int, str] = {
    0: 'ST1.HH_Alarm:Surge Tank 1 High High Level',
    1: 'AS2A.LP_Alarm:Air Stripper 2A Low Pressure',
    2: 'AS2A.HH_Alarm:Air Stripper 2A High High Level',
    3: 'AS2A.Pump.Alarm_CircuitBreaker:Air Stripper 2A Pump Circuit Breaker Trip',
    4: 'AS2A.Pump.Alarm_Overload:Air Stripper 2A Pump Overload',
    5: 'AS2A.Blower.Alarm_CB:Air Stripper 2A Blower Circuit Breaker Trip',
    6: 'AS2B.LP_Alarm:Air Stripper 2B Low Pressure',
    7: 'AS2B.HH_Alarm:Air Stripper 2B High High Level',
    8: 'AS2B.Pump.Alarm_CircuitBreaker:Air Stripper 2B Pump Circuit Breaker Trip',
    9: 'AS2B.Pump.Alarm_Overload:Air Stripper 2B Pump Overload',
    10: 'AS2B.Blower.Alarm_CB:Air Stripper 2B Blower Circuit Breaker Trip',
    11: 'AS1.LP_Alarm:Air Stripper 1 Low Pressure',
    12: 'AS1.HH_Alarm:Air Stripper 1 High High Level',
    13: 'AS1.Pump.Alarm_CircuitBreaker:Air Stripper 1 Pump Circuit Breaker Trip',
    14: 'AS1.Pump.Alarm_Overload:Air Stripper 1 Pump Overload',
    15: 'AS1.Blower.Alarm_CB:Air Stripper 1 Blower Circuit Breaker Trip',
    16: 'STXF1.VFD.Alm_Fault:STXF1 VFD Faulted',
    17: 'STXF1.VFD.EID.Alm_Comms:STXF1 VFD Ethernet Communications Lost',
    18: 'STXF1.VFD.Alm_Run:STXF1 VFD Run Alarm',
    19: 'Sump.HH_Alarm:Sump Pump High High Level',
    20: 'DRW_01.Alarm_NoRun:DRW-01 Run Fault',
    21: 'DRW_02.Alarm_NoRun:DRW-02 Run Fault',
    22: 'DRW_03.Alarm_NoRun:DRW-03 Run Fault',
    23: 'DRW_04.Alarm_NoRun:DRW-04 Run Fault',
    24: 'DRW_05.Alarm_NoRun:DRW-05 Run Fault',
    25: 'DRW_06.Alarm_NoRun:DRW-06 Run Fault',
    26: 'DRW_07.Alarm_NoRun:DRW-07 Run Fault',
    27: 'DRW_08.Alarm_NoRun:DRW-08 Run Fault',
    28: 'DRW_09.Alarm_NoRun:DRW-09 Run Fault',
    29: 'DRW_10.Alarm_NoRun:DRW-10 Run Fault',
    30: 'DRW_11.Alarm_NoRun:DRW-11 Run Fault',
    31: 'DRW_12.Alarm_NoRun:DRW-12 Run Fault',
    32: 'DRW_13.Alarm_NoRun:DRW-13 Run Fault',
    33: 'MRW_14.Alarm_NoRun:MRW-14 Run Fault',
    34: 'MRW_15.Alarm_NoRun:MRW-15 Run Fault',
    35: 'MRW_16.Alarm_NoRun:MRW-16 Run Fault',
    36: 'MRW_17.Alarm_NoRun:MRW-17 Run Fault',
    37: 'MRW_18.Alarm_NoRun:MRW-18 Run Fault',
    38: 'MRW_19.Alarm_NoRun:MRW-19 Run Fault',
    39: 'MRW_20.Alarm_NoRun:MRW-20 Run Fault',
    40: 'MRW_21.Alarm_NoRun:MRW-21 Run Fault',
    41: 'MRW_22.Alarm_NoRun:MRW-22 Run Fault',
    42: 'SRW_23.Alarm_NoRun:SRW-23 Run Fault',
    43: 'SRW_24.Alarm_NoRun:SRW-24 Run Fault',
    44: 'SRW_25.Alarm_NoRun:SRW-25 Run Fault',
    45: 'SRW_26.Alarm_NoRun:SRW-26 Run Fault',
    46: 'SRW_27.Alarm_NoRun:SRW-27 Run Fault',
    47: 'SRW_28.Alarm_NoRun:SRW-28 Run Fault',
    48: 'SRW_29.Alarm_NoRun:SRW-29 Run Fault',
    49: 'SRW_30.Alarm_NoRun:SRW-30 Run Fault',
    50: 'Node1_EIP.Alm_Comms:Keyence Node 1 Communications Alarm',
    51: 'Node2_EIP.Alm_Comms:Keyence Node 2 Communications Alarm',
    52: 'Node3_EIP.Alm_Comms:Keyence Node 3 Communications Alarm',
    53: 'Node4_EIP.Alm_Comms:Keyence Node 4 Communications Alarm',
    54: 'Node5_EIP.Alm_Comms:Keyence Node 5 Communications Alarm',
    55: 'Node6_EIP.Alm_Comms:Keyence Node 6 Communications Alarm',
    56: 'Node7_EIP.Alm_Comms:Keyence Node 7 Communications Alarm',
    57: 'Node8_EIP.Alm_Comms:Keyence Node 8 Communications Alarm',
    58: 'Node9_EIP.Alm_Comms:Keyence Node 9 Communications Alarm',
    59: 'Alm_GD_BlowerOff:Zone 1 and 2 Air Pressure Loss. Check Gardner Denver Blower'
}
