# Generated by Django 4.1.2 on 2022-11-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_receives_alert_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receives_text_alerts',
            field=models.BooleanField(default=False, help_text='Indicates whether user should receive text notifications of alarms'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='text_to_address',
            field=models.CharField(blank=True, help_text='Example: 5554441111@txt.att.net (Consult online for carrier-specific information', max_length=50),
        ),
    ]
