# Generated by Django 4.1.2 on 2022-11-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_receives_text_alerts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='text_to_address',
            field=models.CharField(blank=True, help_text='Example: 5554441111@txt.att.net (Consult online for carrier-specific information)', max_length=50),
        ),
    ]
