# Generated by Django 4.1 on 2022-09-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plc_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welllogentry',
            options={'verbose_name': 'Well Log Entry', 'verbose_name_plural': 'Well Log Entries'},
        ),
    ]
