# Generated by Django 4.1 on 2022-10-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc_logs', '0002_alter_welllogentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='welllogentry',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
