# Generated by Django 4.1 on 2022-10-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc_logs', '0003_welllogentry_is_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welllogentry',
            name='gal_per_minute',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='welllogentry',
            name='is_running',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='welllogentry',
            name='total_gal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
