# Generated by Django 4.1.2 on 2022-10-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc_logs', '0004_alter_welllogentry_gal_per_minute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='welllogentry',
            name='pump_mode',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=20),
        ),
    ]
