# Generated by Django 4.1.2 on 2022-10-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc_logs', '0005_welllogentry_pump_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welllogentry',
            name='gal_per_minute',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='welllogentry',
            name='total_gal',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
    ]
