# Generated by Django 4.1.2 on 2022-11-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc_logs', '0006_alter_welllogentry_gal_per_minute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirStripperLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_stripper_name', models.CharField(max_length=25)),
                ('pump_runtime', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True, verbose_name='Pump Runtime')),
                ('blower_runtime', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True, verbose_name='Blower Runtime')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Air Stripper Log Entry',
                'verbose_name_plural': 'Air Stripper Log Entries',
            },
        ),
    ]
