# Generated by Django 4.1.2 on 2022-11-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc_logs', '0007_airstripperlogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardnerDenverBlowerLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_pre_air_filter_vacuum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Intake Pre Air Filter Vacuum')),
                ('intake_temp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Intake Temperature')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gardner Denver Blower Log Entry',
                'verbose_name_plural': 'Gardner Denver Blower Log Entries',
            },
        ),
        migrations.CreateModel(
            name='HeatExchangerLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('flow_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('outlet_air_temp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Outlet Air Temperature')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Heat Exchanger Log Entry',
                'verbose_name_plural': 'Heat Exchanger Log Entries',
            },
        ),
        migrations.CreateModel(
            name='ZoneFlowLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_flow_right', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Zone 1 and 2 Flow Right Side')),
                ('zone_flow_left', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Combined Flow (Left Side)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zone Flow Log Entry',
                'verbose_name_plural': 'Zone Flow Log Entries',
            },
        ),
    ]
