# Generated by Django 4.1.2 on 2022-11-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc_logs', '0008_gardnerdenverblowerlogentry_heatexchangerlogentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeWaterLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('flow_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discharge Water Log Entry',
                'verbose_name_plural': 'Discharge Water Log Entries',
            },
        ),
        migrations.CreateModel(
            name='SurgeTankLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('flow_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Surge Tank Log Entry',
                'verbose_name_plural': 'Surge Tank Log Entries',
            },
        ),
    ]
