# Generated by Django 4.1 on 2022-09-26 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc_alarms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plcalarm',
            name='is_cleared',
        ),
        migrations.AddField(
            model_name='plcalarm',
            name='alarm_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plcalarm',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plcalarm',
            name='timestamp_acknowledged',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='plcalarm',
            name='timestamp_cleared',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='plcalarm',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
