# Generated by Django 4.1 on 2022-09-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc_alarms', '0002_remove_plcalarm_is_cleared_plcalarm_alarm_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plcalarm',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plcalarm',
            name='timestamp_acknowledged',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plcalarm',
            name='timestamp_cleared',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
