# Generated by Django 4.1 on 2022-09-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plc_alarms', '0003_alter_plcalarm_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plcalarm',
            options={'verbose_name': 'PLC Alarm', 'verbose_name_plural': 'PLC Alarms'},
        ),
    ]
