# Generated by Django 4.1 on 2022-09-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc_alarms', '0004_alter_plcalarm_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plcalarm',
            constraint=models.UniqueConstraint(fields=('tag_name', 'timestamp'), name='unique_tag_name_timestamp'),
        ),
    ]
