# Generated by Django 4.1.2 on 2022-11-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc_alarms', '0005_plcalarm_unique_tag_name_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='plcalarm',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
