# Generated by Django 4.1.2 on 2022-11-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc_alarms', '0006_plcalarm_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='plcalarm',
            name='email_sent_counter',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
