# Generated by Django 4.1.2 on 2022-11-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc_alarms', '0007_plcalarm_email_sent_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='plcalarm',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='plcalarm',
            name='receives_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
