# Generated by Django 4.1 on 2022-09-23 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WellConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('tag_prefix', models.CharField(max_length=50)),
                ('cycle_gallons', models.PositiveIntegerField(help_text='Gallons per cycle')),
                ('sleep_minutes', models.PositiveIntegerField(help_text='Minutes to sleep before restarting cycle')),
                ('record_minutes', models.PositiveIntegerField(default=10, help_text='How many minutes between saving readings to database, between 10 and 360', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(360)])),
            ],
        ),
        migrations.AddConstraint(
            model_name='wellconfig',
            constraint=models.CheckConstraint(check=models.Q(('record_minutes__range', (10, 360))), name='plc_config_WellConfig_record_minutes_range'),
        ),
    ]
