# Generated by Django 4.1 on 2022-09-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plc_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wellconfig',
            options={'verbose_name': 'Well Configuration', 'verbose_name_plural': 'Well Configuration Entries'},
        ),
    ]
