# Generated by Django 4.1 on 2022-10-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellconfig',
            name='tag_prefix',
            field=models.CharField(help_text='The tag name as it appears in the PLC', max_length=50),
        ),
    ]
