# Generated by Django 4.1 on 2022-10-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc_config', '0002_alter_wellconfig_tag_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellconfig',
            name='cycle_gallons',
            field=models.FloatField(default=0, help_text='Gallons per cycle'),
        ),
        migrations.AlterField(
            model_name='wellconfig',
            name='sleep_minutes',
            field=models.FloatField(default=0, help_text='Minutes to sleep before restarting cycle'),
        ),
    ]
