# Generated by Django 4.1.2 on 2022-10-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc_config', '0003_alter_wellconfig_cycle_gallons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirStripperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_stripper_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('tag_prefix', models.CharField(help_text='The tag name as it appears in the PLC', max_length=50)),
            ],
            options={
                'verbose_name': 'Air Stripper Configuration',
                'verbose_name_plural': 'Air Stripper Configuration Entries',
            },
        ),
    ]
